HW5_t1-5
kasyanl/kasyanljgintensive pull request #10
Opened 2020-12-24 09:52 UTC by kasyanl

2020-12-24 14:41 UTC, barilo-egor requested changes

2020-12-24 14:41 UTC, barilo-egor commented on homework5/task1/src/main/java/bean/Counter.java
> +        if (value <= 100) value += step;
> Условие: Если результат сложения текущего состояния счетчика и шага больше 100, тогда операцию не выполнять;

Что будет, если value == 100?

2020-12-24 14:41 UTC, barilo-egor commented on homework5/task1/src/main/java/bean/Counter.java
> +        if (value >= 0) value -= step;
То же самое. Если value будет 0, то получится -1.

2020-12-24 14:41 UTC, barilo-egor commented on homework5/task1/src/main/java/bean/Counter.java
> +        this.step = step;
> setStep() - переопределение шага;
> 
> Условие: Значение должно быть в диапазоне 1 .. 10;

2020-12-24 14:41 UTC, barilo-egor commented on homework5/task2/src/test/java/bean/BookTest.java
> +      assertEquals(expected, actual);
Ты не использовал тестируемый метод)

2020-12-24 14:41 UTC, barilo-egor commented on homework5/task2/src/main/java/bean/Book.java
> +
Не забывай про конструктор без аргументов.

2020-12-27 15:32 UTC, kasyanl commented on homework5/task2/src/main/java/bean/Book.java
> +
конструктор без аргументов является кодсмелсом

2021-01-12 20:15 UTC, merged